# Generated by Django 3.2.3 on 2021-05-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='Produto',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
