# Generated by Django 3.2.3 on 2021-05-29 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto_app', '0004_alter_produtos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='Valor',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
